### ISSUE TITLE
Support XML/AppSettings configuration

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog-sinks-splunk#10]
Moved from: https://github.com/serilog/serilog/issues/577

> Is there no way to configure the Splunk sink using appsettings?

**Comment by arielcloud** [comment]
is there any  progress with that? it's useless until we could use it on appsettings, since no one want it's localhost logs on splunk...

or any workaround? 10x

**Comment by merbla** [comment]
Include general testing and enhancements for https://github.com/serilog/serilog-settings-configuration

**Comment by kevindqc** [comment]
With `Serilog.Settings.Configuration`, sample configuration:

```
{
  "Serilog": {
    "Using": [ "Serilog.Sinks.ColoredConsole", "Serilog.Sinks.AsyncRollingFile", "Serilog.Sinks.Splunk" ],
    "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "Microsoft": "Information",
        "System": "Information"
      }
    },
    "WriteTo": [
      { "Name": "ColoredConsole" },
      { "Name": "AsyncRollingFile", "Args": {
          "pathFormat": "Logs/Sample - {Date}.txt"
        }
      },
      { "Name": "EventCollector", "Args": {
          "splunkHost": "http://localhost:8088/services/collector",
          "eventCollectorToken": "111111111-1111-1111-1111-111111111111"
        }
      }
    ],
    "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ],
    "Properties": {
      "Application": "Sample"
    }
  }
}
```

**Comment by merbla** [comment]
As per @kevindqc notes above and in #87 `appsettings.json` example in README of #92.

**Comment by willapp** [comment]
Why was this closed when the issue relates to XML appsettings and the solution given is only for appsettings.json? Is there any way to set Splunk sink configuration in traditional ASP.NET applications via Web.config XML appsettings?

**Comment by merbla** [comment]
@willapp support should be there provided by the `Serilog.Settings.AppSettings` package.  However this would be .Net Core specific.  Are you thinking `4.5` etc?

**Comment by Grynet** [comment]
> @willapp support should be there provided by the `Serilog.Settings.AppSettings` package. However this would be .Net Core specific. Are you thinking `4.5` etc?

I'm also interested in this. 

Serilog web.config example for .netframework using splunk sunk
