### ISSUE TITLE
Any work/thoughts on Core CLR support?

### ISSUE THREAD

**Issue by colin-young** [serilog/serilog-sinks-splunk#11]
Has anything been done for this sink to determine the level of effort or tasks to support Core CLR & Serilog 2.0.0? Even if somebody had a list of general things that might need to change when upgrading a sink.

I'm not in any immediate need, but it would be kind of fun to see it running. If I get some time in the next few months I might take a crack at it, but I don't want to duplicate efforts if anyone has done any background work.

Colin

**Comment by merbla** [comment]
@colin-young I was waiting until the 2.0 lifting was done. (no excuses now :smiley: ).   I must admit, there is a strong case to drop the TCP/UDP support and rely solely on HTTP Event collector.

The HTTP sink will port quite simply as it is just a HTTP client.

**Comment by colin-young** [comment]
Let me know what I can do to help out. At work we're starting to use Splunk for some internal stuff and it would be nice to be able to support it in the new logging library I'm building for our standard products. Unfortunately we have a heterogeneous platform for our products so we can't just use Seq.

I'm just curious to see how Serilog looks in Splunk. I've got a pretty decent test harness set up so it will be easy for me to drop in a new sink and put it through its paces.

**Comment by merbla** [comment]
Closed by #14 

https://www.nuget.org/packages/Serilog.Sinks.Splunk/2.0.0-rc-77

**Comment by colin-young** [comment]
Nice! Will check that out.
