### ISSUE TITLE
What is the default sourceType?

### ISSUE THREAD

**Issue by VictorioBerra** [serilog/serilog-sinks-splunk#117]
I am a little new with Splunk, I have asked our admin to generate a HEC token for use in my app, and he asked what Source Type the HEC Token needed to be configured for. Does this Sink have a default that I can give my admin? Will "JSON" work for now?

This is a default ASPNET Core 3.1 app.

Thanks

**Comment by merbla** [comment]
Hi @VictorioBerra,

Sorry I have been away on holidays.

Sourcetype can be set in a variety of methods.

* [During configuration](https://github.com/serilog/serilog-sinks-splunk/blob/dev/src/Serilog.Sinks.Splunk/SplunkLoggingConfigurationExtensions.cs#L55)
* At the event level using a custom field (sourcetype)
* or also in the creation of the HEC token (within Splunk itself)

As for 3.1 Core, I personally have not used the sink with that framework.  I am in the process of a PR to update to the latest framework.

Cheers

**Comment by VictorioBerra** [comment]
Your sink seems to work just fine for me under core 3.1. thanks for replying. I set the source type to JSON during HEC creation. I think it was a mandatory selection.
