### ISSUE TITLE
Dead link in Epoch comment

### ISSUE THREAD

**Issue by VictorioBerra** [serilog/serilog-sinks-splunk#119]
https://github.com/serilog/serilog-sinks-splunk/blob/6d75f1886fc91c0380170ad62620218e278ee1eb/src/Serilog.Sinks.Splunk/Sinks/Splunk/Epoch.cs#L29

I cant seem to get to http://dev.splunk.com/view/SP-CAAAE6P

**Comment by merbla** [comment]
I believe this might be the new home - https://docs.splunk.com/Documentation/Splunk/8.0.1/Data/FormateventsforHTTPEventCollector#Event_metadata of that info.
