### ISSUE TITLE
Settings messagehandler from json configuration

### ISSUE THREAD

**Issue by ploef** [serilog/serilog-sinks-splunk#120]
Hi,

Is it possible to set the Splunk messagehandler using the json configuration?

Regards,
Peter

**Comment by merbla** [comment]
Hi @ploef,

I am not aware of an easy way to do this.

Sounds like a good feature.

**Comment by merbla** [comment]
Closing as a part of larger Serilog contrib reorg

Checkout serilog/serilog#1627

**Comment by Oninaig** [comment]
Is there still no way to do this?
