### ISSUE TITLE
Unable to add an outputTemplate

### ISSUE THREAD

**Issue by anishgk80** [serilog/serilog-sinks-splunk#132]
Hi,
Option to add outputTemplate is not available in version 3.4.0. Is there any way to have this option available or is this no more supported ?

**Comment by HakanL** [comment]
Since Splunk is using the concept of key/value properties (same as SEQ) there's no need for an output template.

**Comment by merbla** [comment]
Closing as a part of larger Serilog contrib reorg

Checkout serilog/serilog#1627
