### ISSUE TITLE
Can I configure how often data is sent to splunk?

### ISSUE THREAD

**Issue by mastoj** [serilog/serilog-sinks-splunk#141]
There seems to be some delay from writing the log to when it shows up in splunk, is it possible to configure that delay somehow?

**Comment by VictorioBerra** [comment]
+1

**Comment by merbla** [comment]
Closing as a part of larger Serilog contrib reorg

Checkout serilog/serilog#1627

**Comment by VictorioBerra** [comment]
@merbla what does the reorg have to do with this issue? Why close?
