### ISSUE TITLE
Method Not Found ...EventCollector

### ISSUE THREAD

**Issue by madrum** [serilog/serilog-sinks-splunk#143]
I'm getting this logging error on a couple servers, but not on the majority (> 50). It is affecting a Windows Server 2016 Standard with .Net 4.6.2 and a Windows Server 2012 R2 Standard .Net 4.6.1. I am not aware of any differences specific to these servers.

I have updated all the NuGet packages and I'm not sure what else to look at. 

System.MissingMethodException: Method not found: 'Serilog.LoggerConfiguration Serilog.SplunkLoggingConfigurationExtensions.EventCollector(Serilog.Configuration.LoggerSinkConfiguration, System.String, System.String, System.String, System.String, System.String, System.String, System.String, Serilog.Events.LogEventLevel, System.IFormatProvider, Boolean, Int32, Int32, System.Nullable`1<Int32>, System.Net.Http.HttpMessageHandler, Serilog.Core.LoggingLevelSwitch)'.

**Comment by merbla** [comment]
Closing as a part of larger Serilog contrib reorg

Checkout serilog/serilog#1627
