### ISSUE TITLE
Breaking changes between 3.7.0 and 4+

### ISSUE THREAD

**Issue by b-mcbride** [serilog/serilog-sinks-splunk#197]
Are there known issues or breaking changes between release 3.7.0 and 4+. When using 3.7.0 we are seeing data reach Splunk. When using 4+ no data appears to reaching Splunk.  Here is what the project file looks like...
![image](https://github.com/serilog-contrib/serilog-sinks-splunk/assets/12139862/e7737333-eb20-47be-8a8a-1d37428f25bf)

**Comment by b-mcbride** [comment]
I resolved this myself. The issue was related to new Splunk paths.  Version 3.7.0 used URI path of `services/collector`. 4+ uses `services/collector/event`. I updated the configuration and things began working again.

**Comment by EEParker** [comment]
There were other breaking changes if you were using `Serilog.Sinks.PeriodicBatching`. Happy to see you figured this one out.

**Comment by EEParker** [comment]
Added here https://github.com/serilog-contrib/serilog-sinks-splunk/wiki#400-breaking-changes

**Comment by b-mcbride** [comment]
Appreciate the response!
