### ISSUE TITLE
Update Serilog.Sinks.PeriodicBatching to Version 4.1.0

### ISSUE THREAD

**Issue by FrankBirkmann** [serilog/serilog-sinks-splunk#201]
Hello,

we have a problem with memory leaks when using Serilog.Sinks.Splunk because there is a bug in Serilog.Sinks.PeriodicBatching 4.0.x (see https://github.com/serilog/serilog-sinks-periodicbatching/issues/76). A version with a corresponding bug fix has already been published there. 

Could you please update the package reference to the new version 4.1.0?
Or should i do a PR?

**Comment by EEParker** [comment]
https://github.com/serilog-contrib/serilog-sinks-splunk/pull/202

**Comment by EEParker** [comment]
https://github.com/serilog-contrib/serilog-sinks-splunk/releases/tag/4.1.0

https://www.nuget.org/packages/Serilog.Sinks.Splunk/4.1.0

This has been released to nuget. Thanks for the reminder :D
