### ISSUE TITLE
Update 3.7.0 -> 4.1.0 not working

### ISSUE THREAD

**Issue by HalHaynes** [serilog/serilog-sinks-splunk#207]
While updating a variety of packages in my application, I updated Serilog.Sinks.Splunk from 3.7.0 to 4.1.0 and discovered that nothing was getting written to Splunk after that. I found the breaking change at https://github.com/serilog-contrib/serilog-sinks-splunk/wiki that says to change `services/collector` to `services/collector/event`, so I did that. But it didn't work. I reverted to my previous commit and the Splunk logging started to happen again.

**Comment by EEParker** [comment]
What version of SPLUNK are you using?

**Comment by EEParker** [comment]
Also, as a note this enhancement will probably be relevant. 
https://github.com/serilog-contrib/serilog-sinks-splunk/issues/205#issuecomment-2130025620

**Comment by marqueh** [comment]
Had the same issue, I've manually set the uriPath to "services/collector" and worked. Splunk version 9.1.2308.203

**Comment by EEParker** [comment]
I'm going to close this issue and use 205 for tracking the work.

**Comment by HalHaynes** [comment]
Splunk Enterprise 9.1.4

May 28, 2024 11:12:40 Jeff Parker, PE ***@***.***>:
