### ISSUE TITLE
Addition Samples

### ISSUE THREAD

**Issue by MGillson** [serilog/serilog-sinks-splunk#25]
I have this Splunk setting in Log4Net
Not sure how to do in serilog
Specifically the meta data in facility and identity shown in the configuration below
`<log4net>
    <root>
      <level value="DEBUG" />
      <appender-ref ref="syslogger" />
    </root>
    <appender name="syslogger" type="log4net.Appender.RemoteSyslogAppender">
      <RemoteAddress value="logs.chugachelectric.com" />
      <RemotePort value="514" />
      <facility value="daemons" />
      <identity value="%P{log4net:HostName} %logger" />
      <layout
        type="log4net.Layout.PatternLayout"
        value="[%level] %m%n"
      />
    </appender>
  </log4net>`

**Comment by merbla** [comment]
Hi @MGillson,

I am not super familiar with Log4Net these days.

There are some example over at https://github.com/serilog/serilog-sinks-splunk/blob/dev/sample/Program.cs#L57.  This uses property enrichment to set extra context for an app, so I guess something like the extension below might be what you are after.

```
.Enrich.WithProperty("Facility", "daemons")
```

The pic below is using the [docker](https://github.com/serilog/serilog-docker/blob/master/console-sample/src/Program.cs#L17) example to set the app name.

![image](https://cloud.githubusercontent.com/assets/637298/16543017/40a0b3b2-4103-11e6-8059-5dcebee6c0ac.png)

Also available are the [enrichers](https://github.com/serilog/serilog/wiki/Enrichment) that will add host name etc.  You can also write your own enrichers to set context specific to your app.

HTH!

**Comment by MGillson** [comment]
Thanks for your reply. 

At work, he said his log4net is using UDP which is different than the
event call. 

On 2016-07-02 3:54 pm, Matthew Erbs wrote: 

> Hi @MGillson [1], 
> 
> I am not super familiar with Log4Net these days. 
> 
> There are some example over at https://github.com/serilog/serilog-sinks-splunk/blob/dev/sample/Program.cs#L57 [2]. This uses property enrichment to set extra context for an app, so I guess something like the extension below might be what you are after. 
> 
> .Enrich.WithProperty("Facility", "daemons")
> 
> The pic below is using the docker [3] example to set the app name. 
> 
> [4] 
> 
> Also available are the enrichers [5] that will add host name etc. You can also write your own enrichers to set context specific to your app. 
> 
> HTH! 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [6], or mute the thread [7].

 

Links:
------
[1] https://github.com/MGillson
[2]
https://github.com/serilog/serilog-sinks-splunk/blob/dev/sample/Program.cs#L57
[3]
https://github.com/serilog/serilog-docker/blob/master/console-sample/src/Program.cs#L17
[4]
https://cloud.githubusercontent.com/assets/637298/16543017/40a0b3b2-4103-11e6-8059-5dcebee6c0ac.png
[5] https://github.com/serilog/serilog/wiki/Enrichment
[6]
https://github.com/serilog/serilog-sinks-splunk/issues/25#issuecomment-230127769
[7]
https://github.com/notifications/unsubscribe/AAHGAKEx-pI27dXtfCiSeawO-kdTY1HUks5qRvorgaJpZM4JDcqd

**Comment by merbla** [comment]
Hi @MGillson any more info on this one? I

**Comment by MGillson** [comment]
No. Current not working with .NET Core in production. 

Eventually we will go that way. 

On 2016-08-07 7:38 pm, Matthew Erbs wrote: 

> Hi @MGillson [1] any more info on this one? I 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

 

Links:
------
[1] https://github.com/MGillson
[2]
https://github.com/serilog/serilog-sinks-splunk/issues/25#issuecomment-238135277
[3]

**Comment by merbla** [comment]
Thanks @MGillson closing this for now.
