### ISSUE TITLE
Update to use VS2017/.Net Core tooling

### ISSUE THREAD

**Issue by patriklindstrom** [serilog/serilog-sinks-splunk#47]
I get errors like: src\sample\project.json: Failed to migrate XProj project Sample. Could not find project.json at L:\Dev\serilog-sinks-splunk\src\sample\project.json.  
and
serilog-sinks-splunk.sln: Visual Studio needs to make non-functional changes to this project in order to enable the project to open in released versions of Visual Studio newer than Visual Studio 2010 SP1 without impacting project behavior.

**Comment by merbla** [comment]
Hi @patriklindstrom,

Thanks for dropping by.  I assume you are opening this within the latest VS2017 with .Net Core tooling support.  We are working through this in all our repos/sinks (>50) however it is taking some time.  Please bear with us.

Please feel free to provide a PR, we have just not got to this sink as yet.

The change would include not just files but updates to 
* Tests
* Build (yaml)
* TFM

**Comment by patriklindstrom** [comment]
@merbla thanks for quick reply. Ill try to look into it.

**Comment by merbla** [comment]
I will dig around another sink conversion as an example.

**Comment by patriklindstrom** [comment]
I found this info for the error for Visual Studio  ".NET Cord SDK Not found...."  https://github.com/aspnet/Tooling/blob/master/known-issues-vs2015.md#missing-sdk . See if it will help me get further.

**Comment by merbla** [comment]
Reference [PR]( https://github.com/serilog/serilog-formatting-compact-reader/pull/10) for migration.

**Comment by merbla** [comment]
Fixed in #48 & #49
