### ISSUE TITLE
CompactJsonFormatter is not working with Splunk EventCollector Sink

### ISSUE THREAD

**Issue by avireddy02** [serilog/serilog-sinks-splunk#52]
Splunk EventCollector Sink is not working with CompactJsonFormatter. Looks like it's not generating Event attribute.

Error: A status code of BadRequest was received when attempting to send to http://localhost:8088/services/collector. The event has been discarded and will not be placed back in the queue.

**Comment by merbla** [comment]
Hi @avireddy02,

The BAD Request will be related to the `CompactJsonFormatter` not creating the payload as per the HEC endpoint definition. See thess 

* [Format events for HTTP Event Collector](http://dev.splunk.com/view/event-collector/SP-CAAAE6P)
* [Getting data in with HTTP Event Collector](http://dev.splunk.com/view/event-collector/SP-CAAAE7G).

By default, a formatter is included with the Sink [here](https://github.com/serilog/serilog-sinks-splunk/blob/dev/src/Serilog.Sinks.Splunk/Sinks/Splunk/SplunkJsonFormatter.cs#L28).

In particular check out [this line](https://github.com/serilog/serilog-sinks-splunk/blob/dev/src/Serilog.Sinks.Splunk/Sinks/Splunk/SplunkJsonFormatter.cs#L106), you can see some specific properties set in the JSON.

HTH.

**Comment by merbla** [comment]
@avireddy02 if you think a compact formatter is worthwhile, please feel free to submit a PR with a subclassed formatter specific for Splunk.

**Comment by merbla** [comment]
Fixed in #57

**Comment by avireddy02** [comment]
@merbla 

public CompactSplunkJsonFormatter(bool renderTemplate = false, string source = null, string sourceType = null, string   **_host_** = null, string index = null)

When host is not specified, can we default host to Dns.GetHostName()?

**Comment by merbla** [comment]
That sounds reasonable.
