### ISSUE TITLE
The event collector ignores the outputTemplate

### ISSUE THREAD

**Issue by JaimeReynoso** [serilog/serilog-sinks-splunk#64]
The event collector ignores the output template option. It does not render the output template specified

**Comment by merbla** [comment]
Hi @JaimeReynoso,

Do you have a quick repo of the problem

Thanks!

**Comment by merbla** [comment]
Hi @JaimeReynoso,

Any chance for some code to repo the problem?

**Comment by eaardal** [comment]
Hi I see the same problem. You can use the test-repo I used for playing with this: https://github.com/eaardal/SerilogDemo/tree/output-template

Result I see in Splunk vs template I see in console

![serilog_splunk_outtemp](https://user-images.githubusercontent.com/2316274/33377502-f9bd1a68-d511-11e7-9018-f91a16de34e3.PNG)

**Comment by gabrielweyer** [comment]
Structured Sinks don't support `outputTemplate`. If you look at [`SplunkLoggingConfigurationExtensions`](https://github.com/serilog/serilog-sinks-splunk/blob/dev/src/Serilog.Sinks.Splunk/SplunkLoggingConfigurationExtensions.cs) you'll see than the parameter `outputTemplate` is never used.

It makes sense to remove the `outputTemplate` parameter, thoughs?

**Comment by eaardal** [comment]
Yeah if it's not supported it shouldn't look like it is imo. Either remove or mark as [Obsolete] with explanation?

**Comment by merbla** [comment]
Removing FTM, however using the [raw](http://dev.splunk.com/view/event-collector/SP-CAAAE8Y#raw) endpoint would allow this to be a use case.
