### ISSUE TITLE
Missing SplunkViaTcp and SplunkViaUdp functionality in .NET Core package version

### ISSUE THREAD

**Issue by sshows** [serilog/serilog-sinks-splunk#65]
Noticed the .NET Core package is missing the extensions to the SplunkViaTcp and SplunkViaUdp functionality. Are there any plans for that to be added?

**Comment by merbla** [comment]
Hi @sshows,
Thanks for dropping by.  Initially the .Net Core (first versions) did not have libraries/APIs in place to support some of the protocols.

Now that [Dot Net Core 2.0](https://github.com/dotnet/announcements/issues/24) is out, this could be a possibility.

Generally, we have had more requirements/requests around the HEC endpoint however if TCP/UDP is still in demand then it is something we should look into.

HTH

**Comment by Caldas** [comment]
Hi, any idea when TCP and UDP will be avaiable?

**Comment by andiexer** [comment]
would love to see udp support as well. maybe try to implement it by myself.

**Comment by merbla** [comment]
Currently in `net45` TCP/UDP is implemented via `Splunk.Logging.Common`.  This package does not currently target .Net Core (`netstandard1/2`).   

Details at
* https://www.nuget.org/packages/Splunk.Logging.Common/1.6.0
* https://github.com/splunk/splunk-library-dotnetlogging/issues/24

Options are to drop the package and implement or wait for an update.

Thoughts?

**Comment by vstribrny** [comment]
It's sad that guys from Spulk are not willing to upgrade from  netfw to netcore/netstandard. For version 2 onwards, it should not be a problem I believe.

**Comment by vstribrny** [comment]
I would personally remove that dependency and reimplement...

**Comment by merbla** [comment]
Closing as a part of larger Serilog contrib reorg

Checkout https://github.com/serilog/serilog/issues/1627
