### ISSUE TITLE
System.Threading.Tasks.TaskCanceledException

### ISSUE THREAD

**Issue by sksksksksksk** [serilog/serilog-sinks-splunk#74]
Hi,
I am working with Serilog.Sinks.Splunk's Event Collector and I am getting the "Task Canceled Exception". I think I need to increase the timeout for Http request. Is there any way I can do it ?

**Comment by merbla** [comment]
Hi @sksksksksksk,
What version of the package are you using?

**Comment by sksksksksksk** [comment]
2.1.3

**Comment by merbla** [comment]
Sorry @sksksksksksk,

Just a few more notes.  What target framework are you using? And what sort of app are using?

**Comment by merbla** [comment]
Closing for now, if this pops up again we can re-open. 

Need some code to reproduce.
