### ISSUE TITLE
System.Net.Http NuGet Reference in .NET Framework 4.7.1

### ISSUE THREAD

**Issue by Blackbaud-JeffDye** [serilog/serilog-sinks-splunk#77]
Hey y'all, using this sink in a full .net framework app (even 4.7.1) seems to pull in the System.Net.Http nuget package (v4.3.2) which can cause all kinds of reference errors and assembly binding issues, along with dependencies on a few System.Security.* packages too.  In this case, I think we'd rather use the actual Framework System.Net.Http.

This is similar to this issue in another sink: https://github.com/serilog/serilog-sinks-seq/issues/83
Changeset which resolved that issue: https://github.com/serilog/serilog-sinks-seq/pull/85/files

Would it be possible to remove that package for Framework specifically for 4.7+?

**Comment by merbla** [comment]
@Blackbaud-JeffDye sounds reasonable, just on leave for a few weeks.  Feel free to PR if you need earlier.

**Comment by jeffbdye** [comment]
Sounds good @merbla, I'll give it a try.
