### ISSUE TITLE
Merge System.Net.Http reference changes from dev branch to master?

### ISSUE THREAD

**Issue by Blackbaud-JeffDye** [serilog/serilog-sinks-splunk#80]
Hey, I've done some testing with the prerelease version of this package after having picked up the System.Net.Http reference changes in the dev branch and verified that they allow us to remove the reference to the System.Net.Http nuget package as we wanted, which is great news!

However, I was wondering what all needed to happen to bring those changes over to the master branch? My team is hesitant to ship changes using prerelease versions of nugets, and I saw there were a few other commits that dev had which master did not. Thanks!

**Comment by merbla** [comment]
Not much really, just the PR from `dev` -> `master`.  Let me get that going.  Sorry for the delay I have been on holidays.

**Comment by merbla** [comment]
Hey @Blackbaud-JeffDye,

Give this a go 

* https://www.nuget.org/packages/Serilog.Sinks.Splunk/2.5.0
* https://github.com/serilog/serilog-sinks-splunk/releases/tag/v2.5.0

**Comment by Blackbaud-JeffDye** [comment]
Thank you @merbla!
