### ISSUE TITLE
Support for file buffer?

### ISSUE THREAD

**Issue by runes83** [serilog/serilog-sinks-splunk#82]
Is there support for a file buffer if the http service is down.
The seq Sink implements this.

**Comment by merbla** [comment]
Hey @runes83,

You are correct, there is not currently any buffering/fallback support like Seq or Elastic Search.

This could be a feature if required.

**Comment by merbla** [comment]
Closing as a part of larger Serilog contrib reorg

Checkout https://github.com/serilog/serilog/issues/1627
