### ISSUE TITLE
Split sinks into separate packages/repositories

### ISSUE THREAD

**Issue by merbla** [serilog/serilog-sinks-splunk#88]
Currently the Splunk package caters for three sinks:

* HEC (Supports `netstandard1.1` & `netstandard1.3`)
* TCP (Supports `net45` & depends on `Splunk.Logging.Common` which depends on `Newtonsoft.Json` >= 6.0.8)
* UCP (Supports `net45` & depends on `Splunk.Logging.Common` which depends on `Newtonsoft.Json` >= 6.0.8)

This however introduces issues such as limitations relating to signing dlls (see: #76) & .NetCore support across all sinks (see: #65).  In addition, there is not a clear indication of usage of each sink.

To allow the related sinks to evolve independently, this is a proposal to split the sinks into isolated packages.

*Notes/Considerations*:
* Currently there is not a significant amount of re-used logic/code across sinks
* The majority of features/issues relate to the HEC sink
* Release of future sinks (nova etc.)

## Option 1
Status Quo, all three sinks packaged together and we deal with the issues mentioned

## Option 2
Split sinks and packages into separate repos/packages
* `Serilog.Sinks.Splunk` (HEC Sink) appears to be the most used sink and preference of data ingestion from Splunk itself.
* `Serilog.Sinks.Splunk.Tcp` (TCP Sink)
* `Serilog.Sinks.Splunk.Udp` (UDP Sink)

## Option 3
Introduce meta-packages
* `Serilog.Sinks.Splunk` (Core functionality - not much)
* `Serilog.Sinks.Splunk.HEC` (HEC Sink)
* `Serilog.Sinks.Splunk.Tcp` (TCP Sink)
* `Serilog.Sinks.Splunk.Udp` (UDP Sink)

Thoughts? Other ideas?

**Comment by nblumhardt** [comment]
At least from a project/repository layout point of view, I can see option 3 being easier to fit with the way things are organized today: we could just create two new repos for the `.Tcp` and `.Udp` sinks, and all would be business-as-usual. Not a consumer though, so not sure what my opinion is worth on this one :-D

**Comment by merbla** [comment]
Addressed in #89
