### ISSUE TITLE
No request is made, no error thrown

### ISSUE THREAD

**Issue by mtman** [serilog/serilog-sinks-splunk#95]
### Steps
```powershell
dotnet new console -n serilog-splunk-issue
cd serilog-splunk-issue
dotnet add package serilog
dotnet add package serilog.sinks.splunk
```
Program.cs:
```c#
using System;
using Serilog;

namespace serilog_splunk_issue
{
    class Program
    {
        static void Main(string[] args)
        {
            Serilog.Debugging.SelfLog.Enable(Console.Error);
            
            var log = new LoggerConfiguration()
                .WriteTo.EventCollector("http://192.168.0.11:8088/services/collector", "ea6595dc-72f2-40fd-94c5-c93300dc0158")
                .CreateLogger();

            log.Information("test");
        }
    }
}
```

```powershell
dotnet run
```

### Result

No console output.

No records were added.

Fiddler doesn't show any request to `192.168.0.11`

**Comment by merbla** [comment]
Hi @mtman,

Can you try calling `log.CloseAndFlush()`, under the hood this sink uses the period batching sink so events are not immediately flushed.  Middleware and frameworks such as ASP.Net do this sometimes as the request pipeline level.  You will find similar behaviour in other HTTP sinks.

* https://github.com/serilog/serilog/wiki/Lifecycle-of-Loggers
* http://merbla.com/2016/07/06/serilog-log-closeandflush/

Hope this helps!

**Comment by mtman** [comment]
That was indeed the problem. Thanks a lot.

**Comment by vsix27** [comment]
it looks like there is no method `CloseAndFlush()` anymore... 
i can write message to splunk from curl but not from java or .net core... no errors, ne messages
in curl i have splunkhost  https://localhost:8088/services/collector, in .net/java using https://localhost:8088 (tried with services/collector too)

**Comment by j2jensen** [comment]
@vsix27 `Log.CloseAndFlush()` just calls the `Dispose()` method on the default logger instance. Have you tried calling `Dispose()`?
