### ISSUE TITLE
AWS Serverless Lambda - synchronous logs

### ISSUE THREAD

**Issue by bhavishyachandra** [serilog/serilog-sinks-splunk#96]
Hello

I was using this sink to log to Splunk from my C# Serverless Lambda. We found that the platform kills all background threads after the API response is sent from the controller. This was causing some logs to go missing. Would be great if you could add an additional parameter that makes all the calls to Splunk synchronous in place of the periodic batching. 

Thanks

**Comment by merbla** [comment]
@bhavishyachandra you most likely need to call `Log.CloseAndFlush()` before exiting. 

https://merbla.com/2016/07/06/serilog-log-closeandflush/

**Comment by JoryUK** [comment]
I have a similar problem, i call Log.CloseAndFlush(); in a finally block of the lambda handler.

**Comment by JoryUK** [comment]
I have a similar problem.
Calling Log.CloseAndFlush(); in a finally block in the Handle method.
The faster the lambda execution the less chance i will get any logs written at all...

I have this lambda set to run every minute, it only logs during the cold start which took 1295.98 ms.

**Comment by oguzhancagliyan** [comment]
Did you find a solution?

**Comment by bhavishyachandra** [comment]
@oguzhancagliyan I don't have a solution. we moved away from Lambda and hosted our API in a docker container.

**Comment by lorenh** [comment]
This is proving to be a big problem for us too. When sending logs directly to Splunk from a C# lambda (it's an aspnetcore app) they get dropped if the lambda executes quickly.  Has anyone thought about ways to solve this in a clean way?  Some sort of middleware that flushes on each request?  Is there a way to just "flush" and not close?

**Comment by merbla** [comment]
Closing as a part of larger Serilog contrib reorg

Checkout https://github.com/serilog/serilog/issues/1627

**Comment by skomis-mm** [comment]
Hi @lorenh , 
wrote a snippets [here](https://github.com/serilog/serilog-aspnetcore/issues/210#issuecomment-968370877)
