### ISSUE TITLE
Fallback if network connection is down

### ISSUE THREAD

**Issue by joacar** [serilog/serilog-sinks-splunk#99]
Hi,

I wonder if there are any plans on adding a fallback if the network connection is down? If the log messages cannot be sent across the network, I would like to persist the events to file using `CompatchJsonTextFormatter` and have an agent that probes for any files and send them to the server when the network connection is restored.

Great work!

**Comment by merbla** [comment]
Hey @joacar,

Thanks for the note, there was discussion in #82 to follow the [Seq](https://github.com/serilog/serilog-sinks-seq/blob/dev/src/Serilog.Sinks.Seq/Sinks/Seq/Durable/DurableSeqSink.cs) and other durable sinks approach to this problem.

I will try to get a PR up soon!

**Comment by joacar** [comment]
Cool. Let me know if you need to discuss anything or I can help out it any way!

**Comment by merbla** [comment]
Closing as a part of larger Serilog contrib reorg

Checkout https://github.com/serilog/serilog/issues/1627
